name: "Release"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/claudetainer/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "Install DevContainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Test Claudetainer Feature"
        run: devcontainer features test .

  deploy:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR for Documentation
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated documentation update [skip ci]"
          title: "Automated documentation update"
          body: |
            Automated documentation update generated by the release workflow.
            
            This PR updates the README.md files for published features.
          branch: automated-documentation-update
          delete-branch: true
          add-paths: |
            */**/README.md