name: "Test"
on:
  pull_request:
    paths:
      - 'src/claudetainer/**'
      - 'test/claudetainer/**'
      - 'bin/**'
      - 'build.sh'
      - 'CLAUDE.md'
      - 'README.md'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'src/claudetainer/**'
      - 'test/claudetainer/**'
      - 'bin/**'
      - 'build.sh'
      - 'CLAUDE.md'
      - 'README.md'

jobs:
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Test Modular CLI"
        run: |
          ./bin/claudetainer --version
          ./bin/claudetainer --help >/dev/null
          ./bin/claudetainer prereqs >/dev/null || echo "Prereqs check completed (expected to show missing deps in CI)"

      - name: "Build and Test CLI"
        run: |
          chmod +x build.sh
          ./build.sh
          ./dist/claudetainer --version
          ./dist/claudetainer --help >/dev/null

  test-scenarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "Install DevContainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Test All Scenarios"
        run: devcontainer features test .