name: "Test Claudetainer Feature"
on:
  pull_request:
    paths:
      - 'src/claudetainer/**'
      - 'test/claudetainer/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'src/claudetainer/**'
      - 'test/claudetainer/**'

jobs:
  test-scenarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "Install DevContainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Test All Scenarios"
        run: devcontainer features test .